Js dev
linuxserver/docker-heimdall pull request #77
Opened 2021-04-12 19:05 UTC by aptalca

2021-04-12 19:39 UTC, aptalca commented
Need to use py2 due to this issue with node-sqlite3: https://github.com/mapbox/node-sqlite3/issues/1443

2021-04-12 20:43 UTC, alex-phillips requested changes

2021-04-12 20:43 UTC, alex-phillips commented on Dockerfile
> +  NODE_ENV="development" npm install && \
@aptalca why are you not building in production mode?

2021-04-12 20:43 UTC, alex-phillips commented on root/etc/cont-init.d/50-config
> +    npm run db:migrate
We also need a migrate call after this conditional since existing installations will need migrations run (I know this wasn't in my container).

2021-04-12 20:51 UTC, aptalca commented on Dockerfile
> +  NODE_ENV="development" npm install && \
subsequent `npm run build` fails with `sh: prettier: not found`

2021-04-12 20:58 UTC, alex-phillips commented on Dockerfile
> +  npm run build && \
This needs `NODE_ENV=production` prepended to the build command.

2021-04-12 21:03 UTC, aptalca commented on Dockerfile
> +  npm run build && \
I set it to production globally, then override it during npm install

2021-04-12 21:38 UTC, aptalca commented on root/etc/cont-init.d/50-config
> +    npm run db:migrate
should it run migrate and seed both outside of the if?

2021-04-13 12:12 UTC, alex-phillips commented on root/etc/cont-init.d/50-config
> +    npm run db:migrate
@aptalca No, just the migrate. I believe the seed will double up on settings if run multiple times. I may need to code around this.

2021-04-13 13:43 UTC, alex-phillips approved these changes

2021-04-13 14:35 UTC, merged